#!/usr/bin/env bash

count=0
connected="󰵪"
disconnected="󱦂"

IP="$(/usr/sbin/ifconfig enp0s3 | /usr/bin/grep "inet " | /usr/bin/awk '{print $2}')"

if (ping -c 1 archlinux.org || ping -c 1 google.com || ping -c 1 bitbucket.org || ping -c 1 github.com || ping -c 1 sourceforge.net) &>/dev/null; then
	echo "%{F#2495e7} $connected %{F#ffffff}$IP"
else
	echo "%{F#ff0000}$disconnected Offline" ; sleep 5
fi
