#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config focused_border_color      "#ff00ff"
bspc config active_border_color       "#fb19b0"
bspc config normal_border_color       "#aa94a3"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
feh --bg-fill /home/looping/Pictures/bg.png &	
/home/looping/.config/polybar/launch.sh --hack
picom &
wmname LG3D &
